---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fizo1332/public_html
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/rsync -av --delete \
        --exclude='.git*' \
        --exclude='.cpanel*' \
        --exclude='media/' \
        ./ "$DEPLOYPATH"/
